#!/bin/bash

# Update the instance
yum update -y

# Install Node.js (using Node Version Manager)
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
nvm install node

cd /home/ec2-user
mkdir app
cd app

npm init -y
npm install express

echo "
const express = require('express');
const app = express();

function getRandomInt(min, max) {
    // Generate a random integer between min and max (inclusive)
    min = Math.ceil(min);
    max = Math.floor(max);
    return Math.floor(Math.random() * (max - min + 1)) + min;
}

function isPrime(num) {
    // Check if a number is prime
    if (num <= 1) return false; // 0 and 1 are not prime numbers
    if (num <= 3) return true;  // 2 and 3 are prime numbers

    if (num % 2 === 0 || num % 3 === 0) return false; // Exclude multiples of 2 and 3

    for (let i = 5; i * i <= num; i += 6) {
        if (num % i === 0 || num % (i + 2) === 0) return false;
    }

    return true;
}

function checkRandomPrime(min, max) {
    const randomNumber = getRandomInt(min, max);
    const primeStatus = isPrime(randomNumber);
    return [randomNumber, primeStatus];
}

app.get('/', (req, res) => {
    const [randomNumber, primeStatus] = checkRandomPrime(100000000000, 1000000000000);
    res.send('The random number is ' + randomNumber + '. Is it prime? ' + primeStatus);
});

app.listen(80, () => {
  console.log('Server is running on http://localhost:80');
}); " >> index.js

node index.js
